jobs:
- job: build
  strategy:
    matrix:
      linux:
        POOL: Hosted Ubuntu 1604
      windows:
        POOL: Hosted Windows 2019 with VS2019
      macOS:
        POOL: Hosted macOS
      privateagent:
        POOL: jerick-normal
  pool:
    name: $(POOL)
  variables:  
    YARN_CACHE_FOLDER: $(Pipeline.Workspace)/yarn-cache
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Use Node.js 10'

  - task: RestoreCache@0
    inputs:
      key: |
        $(System.DefaultWorkingDirectory)/yarn.lock
        $(Agent.OS)
      path: '$(YARN_CACHE_FOLDER)'

  - script: yarn
    displayName: 'Install dependencies'

#  - script: yarn build
#    displayName: 'yarn build'

  - task: SaveCache@0
    inputs:
      key: |
        $(System.DefaultWorkingDirectory)/yarn.lock
        $(Agent.OS)
      path: '$(YARN_CACHE_FOLDER)'
