jobs:
- job: build
  strategy:
    matrix:
      linux:
        POOL: Hosted Ubuntu 1604
      windows:
        POOL: Hosted Windows 2019 with VS2019
      windows-nocache:
        POOL: Hosted Windows 2019 with VS2019
        USE_CACHE: FALSE
      macOS:
        POOL: Hosted macOS
      privateagent:
        POOL: jerick-normal
      privateagent-nocache:
        POOL: jerick-normal
        USE_CACHE: FALSE
  pool:
    name: $(POOL)
  variables:  
    YARN_CACHE_FOLDER: $(Pipeline.Workspace)/yarn-cache
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Use Node.js 10'

  - task: RestoreCache@0
    inputs:
      key: |
        $(System.DefaultWorkingDirectory)/yarn.lock
        $(Agent.OS)
      path: '$(YARN_CACHE_FOLDER)'
      cacheHitVar: 'CacheRestored'
    condition: ne(variables['USE_CACHE'], 'FALSE')

  - script: yarn --frozen-lockfile
    displayName: 'Install dependencies'

#  - script: yarn build
#    displayName: 'yarn build'

  - task: SaveCache@0
    inputs:
      key: |
        $(System.DefaultWorkingDirectory)/yarn.lock
        $(Agent.OS)
      path: '$(YARN_CACHE_FOLDER)'
    condition: ne(variables['PipelineCache.CacheRestored'], 'True')

  - script: |
      IF EXIST "%YARN_CACHE_FOLDER%" rmdir /s /q "%YARN_CACHE_FOLDER%"
    condition: eq(variables['POOL'], 'jerick-normal')
    displayName: cleanup
