jobs:
- job: build
  strategy:
    matrix:
      linux:
        POOL: Microsoft-hosted
        VM_IMAGE: ubuntu-16.04
      windows:
        POOL: Microsoft-hosted
        VM_IMAGE: vs2017-win2016
      macOS:
        POOL: Microsoft-hosted
        VM_IMAGE: macOS-10.13
      privateagent:
        POOL: jerick-normal
  pool:
    name: $(POOL)
    vmImage: $(VM_IMAGE)
  variables:  
    YARN_CACHE_FOLDER: $(Pipeline.Workspace)/yarn-cache
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Use Node.js 10'

  - task: RestoreCache@0
    inputs:
      key: |
        $(System.DefaultWorkingDirectory)/yarn.lock
        $(Agent.OS)
      path: '$(YARN_CACHE_FOLDER)'

  - script: yarn
    displayName: 'Install dependencies'

#  - script: yarn build
#    displayName: 'yarn build'

  - task: SaveCache@0
    inputs:
      key: |
        $(System.DefaultWorkingDirectory)/yarn.lock
        $(Agent.OS)
      path: '$(YARN_CACHE_FOLDER)'
