jobs:
- job: yarn
  variables:  
    YARN_CACHE_FOLDER: $(Pipeline.Workspace)/yarn-cache
  steps:
  - restoreCache: $(Build.SourcesDirectory)/yarn.lock
    path: $(YARN_CACHE_FOLDER)

  - script: yarn
    displayName: 'Install dependencies'

#  - script: yarn build
#    displayName: 'Build and test'

  - saveCache: $(Build.SourcesDirectory)/yarn.lock
    path: $(YARN_CACHE_FOLDER)

