jobs:
- job: build
  strategy:
    matrix:
      linux:
        POOL: Hosted Ubuntu 1604
        YARN_OPTIONS: --offline
      linux-nocache:
        POOL: Hosted Ubuntu 1604
        USE_CACHE: FALSE
      windows:
        POOL: Hosted Windows 2019 with VS2019
        YARN_OPTIONS: --offline
      windows-nocache:
        POOL: Hosted Windows 2019 with VS2019
        USE_CACHE: FALSE
      macOS:
        POOL: Hosted macOS
        YARN_OPTIONS: --offline
      macOS-nocache:
        POOL: Hosted macOS
        USE_CACHE: FALSE
      privateagent:
        POOL: jerick-normal
        YARN_OPTIONS: --offline
      privateagent-nocache:
        POOL: jerick-normal
        USE_CACHE: FALSE
  pool:
    name: $(POOL)
  variables:  
    YARN_CACHE_FOLDER: $(Pipeline.Workspace)/yarn-cache
    YARN_OPTIONS: ''
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Use Node.js 10'

  - task: RestoreCache@0
    inputs:
      key: |
        $(System.DefaultWorkingDirectory)/yarn.lock
        $(Agent.OS)
      path: '$(YARN_CACHE_FOLDER)'
      cacheHitVar: 'CacheRestored'
    condition: ne(variables['USE_CACHE'], 'FALSE')

  - script: yarn --frozen-lockfile $(YARN_OPTIONS)
    displayName: 'Install dependencies'

#  - script: yarn build
#    displayName: 'yarn build'

  - task: SaveCache@0
    inputs:
      key: |
        $(System.DefaultWorkingDirectory)/yarn.lock
        $(Agent.OS)
      path: '$(YARN_CACHE_FOLDER)'
    condition: and(ne(variables['USE_CACHE'], 'FALSE'), ne(variables['PipelineCache.CacheRestored'], 'True'))

  - script: |
      IF EXIST "%YARN_CACHE_FOLDER%" rmdir /s /q "%YARN_CACHE_FOLDER%"
      IF EXIST "node_modules" rmdir /s /q "node_modules"
    condition: eq(variables['POOL'], 'jerick-normal')
    displayName: cleanup
